### PR TITLE
Swift 4 Update

### PR DESCRIPTION
**Pull request by ezfe**
I've updated the project to remove all warnings and compile errors under swift 4. I've also reorganized it to fully support the Swift Package Manager. The sample app has been moved to a subdirectory.

The xcodeproject is automatically generated (including it is required for Carthage support), and can be regenerated with `swift package generate-xcodeproj`.

I have tested that Carthage has no issues fetching, and cocoa pods should not either due to changes I made to the `podspec` file

### CODE REVIEW

**Comment by davecom** [comment]
Hi @ezfe ,

Thanks for the contributions. That said, it's probably a good idea to run major reorganizations by a project maintainer before going ahead and doing the work to make a pull request. I'm not up-to-date on the latest changes to SPM's format. It looks like under these changes every new unit test needs to be added to a static `allTests` array in each file... is that what other projects are doing? It seems a little wonky. 

I'm also not a huge fan of separating the sample app from the main project file. Many beginners download zips of project files from GitHub and expect to just be able to "click play" when they open the main project and give up if that doesn't work. I think we could add support for the latest changes to SPM for using SwiftGraph as a dependency without having to rely on it for generation of the Xcode project file. We just did a reorganization of the project to support Carthage... thanks for checking on that before sending this, but I'm still a little hesitant to do yet another reorganization.

Let me know your thoughts. I basically want to understand why the project needs to be completely reorganized again to support the latest changes to SPM, including things like:
- the `allTests` static variables
- separating the project into two Xcode projects
- generating the Xcode project from SPM
- the `LinuxMain.swift` file
- removing the .swift-version file which was (at least for a while - is it still?) required by CocoaPods
- moving sources from `/Sources` to `/Sources/SwiftGraph`

Thanks,
Dave

**Comment by davecom** [comment]
@klundberg thoughts on this re-organization vis-a-vis Carthage?

**Comment by ezfe** [comment]
Hi,

Yes I understand of course that there’s a lot of stuff in here, I didn’t spend too much time on this so don’t worry about that. 

`allTests` and `LinuxMain.swift` are for Linux. My understanding is that because Linux doesn’t have access to Objective-C it doesn’t work the same way. This format is what is provided when you instantiate a new Swift package. 

Generating the Xcode project through SPM isn’t functionally different, just a different way of approaching it.

‘.swift-version’ was my mistake I can re-add that if you choose to make these changes. 

Moving sources was done to follow the new conventions for Swift-PM

Again, please don’t worry about my time when considering these changes. Swift 4 changes themselves are not substantial and these changes are by no means needed.

**Comment by davecom** [comment]
Thanks for the info. Again, I really do appreciate the contributions, I'm just trying to work through all of them. I understand that using SPM to generate the project file is not functionally different, but I just presume that doing so is why you separated the sample app into a different Xcode project?

I'm looking through the documentation about where sources should go. All I see mentioned is sources in `/Sources`. I'm looking [here](https://github.com/apple/swift-package-manager/tree/master/Documentation). I think I'm probably missing something?

I do want to continue to support SPM, I'm just trying to understand what is the minimal amount that is required. I guess the benefit of these changes is that SPM will know about the unit tests. I'm wondering if that can be accomplished without the split. Unfortunately I see very poor documentation about [how testTarget works.](https://github.com/apple/swift-package-manager/blob/master/Documentation/PackageDescriptionV4.md) Is there some better docs somewhere that you've come across? Thanks again.

**Comment by ezfe** [comment]
I've based most of these changes on the templates that can be generated using `swift package init --type library`. These changes are not needed to continue using swift package manager. I believe that the files can be left in `/Sources` though.

Regarding tests, yes you are correct that tests now work both in Xcode and by running `swift test` from the command line. The benefit of that really is just linux support in terms of what can be done.

And yes, I agree that documentation is poor on some features.

You are also correct that is why I moved out the sample app. I was considering proposing moving the sample app to a second repository but I opted for just moving it to a sub-directory.

Again, I understand if these changes are too drastic or unnecessary. Also, as it is your workflow, the change to using `swift package` as your primary control of the package may not be something you want to do at this time.

Thanks for looking at this, though

**Pull request closed without merging**
