### PR TITLE
Change project structure to allow for installation via Carthage

### PR DESCRIPTION
**Pull request by klundberg**
This PR does the following things:

1. Creates a framework target for all the code that was originally in the app target, except for the app delegate.
2. Moves unit tests into a test bundle that points at this new framework instead of the sample app.
3. Makes that framework build-able on any apple platform (macos, ios, tvos, watchos).
4. Removes some code for swift 2.x support, since the latest code in this framework already cannot be built in swift 2.3 mode.

In order to make this code fully build-able with carthage, a new version tag will need to be made at or after this commit, so that carthage can actually get these changes. Specifying 1.2.0 in a cartfile with no later versions available will make carthage get the old version without the extra framework.

### CODE REVIEW

**Comment by davecom** [comment]
Hi @klundberg,
Thanks for the contributions. I'm interesting in merging this as it looks like it doesn't break CocoaPods support, SPM support, or the sample app, as previous attempts to integrate Carthage have. However, I see that the import in Carthage is now `SwiftGraphFramework`. When using it from CocoaPods or SPM, the import is just `SwiftGraph`. Can you make that change to this pull request? Maybe we can rename the sample app target to `SwiftGraphSampleApp`.
My other concern is that I'm not a Carthage user, so what will I have to do in terms of maintenance for continued Carthage support?
Thanks.

**Comment by davecom** [comment]
PS see previous discussions in #4, #8, and #11. I'm really not opposed to adding Carthage support, I just need to be sure it doesn't break anything and need a plan for maintaining it going forward.

**Comment by klundberg** [comment]
Good points, I'll make the requested changes.

The only thing you'd need to do moving forward is make sure the framework builds, that any new files are added to it, and that the scheme for the framework remains shared. Carthage expects the framework target and scheme, and that should be all it needs to get things working.

**Comment by klundberg** [comment]
Just made the change to call the framework target `SwiftGraph` and the example app `SwiftGraphSampleApp`. If you have any other concerns please let me know!

**Comment by klundberg** [comment]
One other thing regarding carthage support: If you ever decide to have SwiftGraph depend on a third party library, this repo would need its own `Cartfile` that points to the version you want, in a similar way that you'd need to specify that in the podspec. Based on your other threads you mentioned, you're not planning to add any dependency there so there shouldn't be a big problem :)

**Comment by davecom** [comment]
Thanks @klundberg. I really appreciate all of the help with this. I'm a little worried, but hopefully nothing is broken. I will release 1.2.1 now so it can be used with Carthage. Thanks again.

**Comment by klundberg** [comment]
Great, thank you!

**Pull request merged**
