### PR TITLE
Protocol-based Implementation

### LINKED ISSUE #21: Experiment with Refactoring Graph from Class to Protocol
In the original version of SwiftGraph, developed under Swift 1, Swift did not support protocol extensions (function implementations in protocols) so it was not particularly useful to make Graph a protocol. I need to see how much existing code would be broken by refactoring Graph into a protocol. Since this would be a large breaking change, it would only be made permanent for version 2.0 of SwiftGraph.

### PR DESCRIPTION
**Pull request by flagello**
Closes #21. Tests are passing.

- Add SwiftLint as a build target and format with SwiftFormat. Not all warnings are fixed, short type names in `Graph`, et al are the only meaningful ones. (fe470fb and 395d5ea)
- Fix Swift 4 warnings in tests (395d5ea).
- Rename the API to be in line with Swift’s [API Design Guidelines](https://swift.org/documentation/api-design-guidelines/). Most methods were renamed to support labels and some of them have changed entirely: `findAll(from:goalTest:)` was renamed to `routes(from:until:)`; the `until` label was used in place of `goalTest` everywhere else; `removeEdge(from:to:bidirectional:)` was renamed to `unedge(:to:bidirectional:)`; `addEdge(from:to:directed:)` was renamed to `edge(:to:directed)`, `detectCycles(upToLength:)` was renamed to `cycles(until:)` so that it’s in line with `edges`, `neighbors`, `routes`; `edgeExists(from:to:)` was renamed to `edged(from:to:)`; `vertexInGraph(vertex:)` was renamed to `contains(vertex:)`, and a `contains(edge:)` was added alongside it.
- Make what previously was `addVertex(:)` to `-> Void` instead of `-> Int` to conform it to the rest of the API. I was also expecting to adopt method chaining but returning `Self` within `Graph` would make it impossible for classes that adopt it to be non-`final`, which may need to be discussed.
- Make `V` conform to `Hashable` instead of `Equatable` because it is used as a `Dictionary.Key` (1add64e, e09493f).
- Remove redundant Sequence conformance. Remove the related `Iterator` typealias and `makeIterator` method because the presence of `index(of:)` and `makeIterator` was causing a segmentation fault. I reported the issue on the Swift issue tracker: [SM-6778](https://bugs.swift.org/browse/SR-6778). `testSequenceTypeAndCollectionType()` is still passing, so the default `makeIterator()` implementation is seemingly working like the previous custom implementation. May need to be double checked?
- Use `mutating` (e09493f, ee105f8, 1da1f83). The protocol-based implementation allowed to mark as `mutating` methods that were previously implemented in a class and were therefore lacking the mutation modifier. ~To work around the `mutating` methods in class-based implementations without needlessly constraining the protocol to `class`, we should refine `mutating` methods with the workaround ([suggested by Kevin Ballard on the Swift mailing list](https://lists.swift.org/pipermail/swift-evolution/Week-of-Mon-20151207/001600.html)) employed by `add(edge:)`. Others method do not yet implement the workaround. I’ll be adding them now.~ (see b150f65)
- Scope utilities that were global and adapt them to instance methods (f8d22ae, a9d971d, c9d3fb6). `distanceArrayToVertexDict` was incorporated into an overload of `dijkstra(root:start:)` that returns a dictionary of vertices and weights instead of an array of weights; `edgesToVertices(edges:graph:)` was generalized to `vertices(from:)`; `pathDictToPath(from:to:pathDict:)` was renamed to `route(from:to:in:)` and was extended; `printMST(edges:graph:)` was made internal and renamed to `printmst(:)`, along with `totalWeight(:)` which was renamed to `weight(of:)`.
- Update tests and sample app to use internal classes that conform to the various protocols. See `Internals.swift`.  

<br>

- ~Due to `Edge` being generic,  types who conform to `UnweightedGraph` and `WeightedGraph ` must implement the `edge(:to:)` requirements by themselves as default implementations via protocol extensions cannot use an `Edge` initializer. This information is described in the documentation of all involved protocols, including `Graph`. A sample implementation is provided in `Internals.swift`.~ (see b150f65)
- Working with generic protocols, implementations are now free of non-ideal internals related to using `Edge` instead of a generic `E`.

Lastly, I’ll refine the documentation, ~add missing `mutating` methods workarounds~, ~and missing tests for newly added methods like`contains(edge:)`~.

~#7 could also be on radar since I’ve now rewritten the API; instead of renaming all the ambiguous methods, we could extend the protocols with `V == Int` and add new signatures for the ambiguous calls; to do so, we encapsulate the logic in internal methods and use it in both methods (moreover the encapsulation is already in place with the `mutating` workaround). It’s not pretty, but I’m not sure I’d want to rename the API to accommodate a single type.~ (see 0dd0c16)

### CODE REVIEW

**Comment by davecom** [comment]
Hi @flagello,

Thanks for the contributions! This is obviously a huge change for the project and it will take me a while to read through and analyze all of it. I wish you had written to me beforehand regarding what you’re working on and submitted the changes more incrementally. I’ll take a look at everyththing as soon as I have time in the next 2 days.
Thanks again,
Dave

**Comment by flagello** [comment]
Please take all the time you need! There’s no rush to review or merge. I was about to use the library and found it was a good opportunity to attempt the protocol-based rewrite. 

Thank you for the suggestion to communicate and work incrementally. Looking back I wouldn’t think there was too much opportunity to split things up, given the fundamentally simple structure, but I see how communicating and gradually submitting changes could have eased the review task.

**Comment by flagello** [comment]
Code coverage is currently at 91.85%. We are missing:
- tests for `mutating` methods because tests use class-based implementations
- a test for a [dijkstra method branch](https://github.com/davecom/SwiftGraph/blob/master/Sources/SwiftGraph/Search.swift#L257)
- tests for [SwiftPriorityQueue](https://github.com/davecom/SwiftPriorityQueue).

**Comment by davecom** [comment]
Hi @flagello ,
Continual thank you for all of the effort here. While I appreciate all of the continued work and enthusiasm, like I said before I really wish you would of approached this in a more incremental manner. This project has been around since Swift 1.2, so it obviously has some cruft and much needed cleanup. However, that doesn't mean that wholesale redoing almost every aspect of the project is what I want to do... At this point, without having had the time to carefully look through all 59 commits, it looks like I think 3/4 of them are great changes but I don't necessarily agree with the other 1/4 or so of what I looked through. This now leaves me in the unenviable position of a) going through 59 commits and figuring out which to merge, b) merging all of them and then reverting either manually or commit by commit the ones that I don't agree with or c) asking you to switch the pull request to an experimental branch where things can be carefully raked through before merging back into master. I also have several overarching concerns:
- This will totally break backwards compatibility for existing users of the project. The project has been around for over 3 years and while it's not taking the world by storm, I do know of at least a dozen people/organizations using it in shipping code.
- The idea was to experiment with `Graph` being protocol based, but I think default implementations of `WeightedGraph` and `UnweightedGraph` (that are not internal but instead open) are important for casual users of the library. They do not want to have to implement a protocol to start using the library. That has been my experience (users never subclass `UnweightedGraph` or `WeightedGraph` — they use them off the shelf... so why would they want to implement a protocol). You can see a version of this project with `Graph` as a protocol but `UnweightedGraph` and `WeightedGraph` remaining classes here:
https://github.com/davecom/ClassicComputerScienceProblemsInSwift/blob/master/Classic%20Computer%20Science%20Problems%20in%20Swift.playground/Pages/Chapter%204.xcplaygroundpage/Contents.swift
- To follow up on the previous, the idea here was to enable use of the library by power users who want to implement a `Graph` protocol. I'm not sure what the big advantage here is of making `UnweightedGraph` and `WeightedGraph` protocols, since one can just subclass the concrete implementations included with the library, other than enabling structs to implement these types.
- I don't like the hack to avoid constraining the protocol to classes. It adds needless complexity. I rather keep it class-only for now and wait for the language to have proper support for mutating in this context. Frankly I think very few if any users of the library care if they can use it with struct let alone enum. It's a nice to have, but not worth the hack IMHO.
- I don't agree with several of the stylistic choices in these commits. It's of course a personal preference, but I guess that's my prerogative. I'll give you a few examples: I prefer vertex/vertices over node/nodes. I prefer addEdge() and removeEdge() over edge() and unedge(). I understand these may go against some Swift guidelines put out on swift.org, but I think they are easier to understand for new users of the library. Those are just some examples, I've seen several others, including some added by SwiftLint that I don't agree with as well.
- Some of the free functions that have been converted into internal methods don't make sense to me. They were utility functions that users of the library may want to use and shouldn't necessarily be tied to a particular type, let alone internal.
- Forcing Vertex type to be `Hashable` instead of `Equatable` puts another burden on users of the library just like forcing them to implement the `UnweightedGraph` or `WeightedGraph` protocols just to use the library does. Frankly many users of Swift do not know how to properly write a hash  function for their custom types that they may use as vertices.

So here's where I'm at:
Pros:
- Better follows some Swift style suggestions
- Allows structs and enums to be graphs
- Code cleanups throughout

Cons:
- Completely breaks compatibility with all existing projects using SwiftGraph
- Harder for new users to use
- Makes stylistic decisions I don't agree with
- Several areas of increased complexity

Perhaps I am missing some other pros?

Ultimately I want this library to be dead simple to use for new users, since many of them are students learning data structures and algorithms, and also dead simple to understand when reading through the code. Some of the contortions that we would have to go through just to get struct and enums to be able to be graphs don't seem worth it to me. And I think it's more useful for most users to have default implementations of `UnweightedGraph` and `WeightedGraph` anyway. So, I'm left really puzzled what I should do here. I think there are some really fantastic changes here, but I don't really want to incorporate many of the overarching big-picture changes. What are your thoughts? Again, I want to thank you for everything you've done. I'm doubtless many of these changes will be incorporated one way or another. 

Again, for the future, this dilemma (that I may not agree with all of your changes, including some of the big overarching ones) is why it's a good idea to communicate first and make pull requests more incremental. Ultimately I'm going to be the one who has to maintain the project going forward... May I ask what your use case is for the project and if you plan to continue to be involved?

Thanks,
David

**Comment by flagello** [comment]
@davecom, thank you for the incredibly thorough response. I truly appreciate it.

Where to start — I wholeheartedly agree with your points and objections. First, I’m sorry if continuing to push changes could have added further cognitive load to your part of the effort. I was mostly working in the open, adjusting as I experimented, both with the public API and the internals themselves. I approached the problem with no thought to backwards compatibility or ergonomics that take into account the typical Swift user or library usage (and that is especially evident if we consider your extremely valid counterpoints to making `UnweightedEdge` and `WeightedEdge` protocols). I intend to personally rely on the library and I have neither backwards compatibility concerns nor ergonomics issues directly related to the, again, valid and practical objections you raised.

I prefer a protocol-based approach despite the shortcomings, but that is a personal preference that should not influence the design direction of the library. I was hoping to contribute something back, and it may very well end up being a net positive for the library even if it’s just a few changes that get merged.

- Regarding SwiftLint and style changes I believe you have every right to stand by your personal preferences. There’s no way out of it. I’d say it’d help to have a default, re-usable standard so that external contributors don’t cause loss of style consistency; and mostly because I’d prefer not to manually format code and keep in mind a reference for each project. But that’s a discussion for another time.
- I converted the free functions to instance methods because I saw they were meant to be used with the graphs themselves or their byproducts. I made them internal thoughtlessly, but that’s a change that’s easily reverted. I didn’t like that the functions were “leaking” into the global scope and especially that they could not be found under’s a graph’s dot autocompletion. I usually learn a new API by autocompleting and exploring from there rather than memorizing all methods and properties from the docs. I also don’t see how having them within a type makes them less accessible, given that they are all generics.
- I believe `Hashable` conformance for `Vertex` would still be needed for #22 to happen. While that is a few steps away, I initially added it because of `distanceArrayToVertexDict<T, W>(distances: [W?], graph: WeightedGraph<T, W>) -> [T: W?]` — as you see, `T` is being used as a `Dictionary.Key`, and a `Dictionary.Key` type must conform to `Hashable`. I’m not sure why the compiler is not catching the issue, and why it has not surfaced before, but it’s there as soon as you convert that function to an instance method where it’s clear whether `T` conforms to `Hashable`. I do agree that it adds inconvenience.

Regarding other changes that will be following up this response and are directly related to your comments:

- Managed to get around the `mutating` problem for classes that were in need of providing implementations for protocol requirements, which is a big plus as it frees us from considerable overhead.
- Renamed things further addressing, ironically, usability issues I encountered with `edge(:to:)` and `unedge(:from:)`. You could give it another look but it’s still quite a bit far from the current API.
- “Solved” #7 once and for all, but that would require subscribing to a substantial part of my approach; still, the solution will work well even if it’s just mirrored onto the current (or adjusted) API as it’s a simple label-based differentiation approach.

Overall, there are a lot of incremental commits and most of them fail to remain within the boundaries that make sense for the library’s direction constraints, either by themselves or because they depend on other changes. I believe not even squashing and cherry-picking would do it.

Let’s handpick changes that may be valuable according to the aforementioned margins. I see:
- More efficient index-based `topologicalSort()`, but not as an overload as that would continue the “type ambiguity” trend.
- isDAG implementation? Along with the minor test additions.
- `Graph` as a protocol.
- `Edge` with `reversed: Self` instead of `reversed: Edge` as it solves issues with using and returning a non-generic `Edge`; but that might mean making `WeightedEdge` and `UnweightedEdge` `final` due to `Self`, and that’s not exactly in line with `open`. We’d have to test it, there might be a workaround (see [here](https://stackoverflow.com/a/39247987/7880059)).

**Comment by davecom** [comment]
Sorry for the very late reply. It looks like there's a lot of good stuff in here. If you want to make individual pull requests for each feature, please do. Thanks!

**Pull request closed without merging**
