### PR TITLE
Make cycle finder return edges

### PR DESCRIPTION
**Pull request by ZevEisenberg**
The functions are duplicated. I don't feel great about that, but I looked into having a shared function that can return cycles or edges, but it either has a bunch of branching or a bunch of time/storage overhead to go from edges to vertices. It seemed better to just leave them separate.

### CODE REVIEW

**Comment by davecom** [comment]
Good stuff — this is awesome, thanks. I may move things around a little bit, but I really appreciate the contribution.

**Comment by ZevEisenberg** [comment]
Oh, also: this _really_ made me want `Graph` to be generic over its `Edge` ;)

**Comment by ZevEisenberg** [comment]
I was bored, so I tried making `Graph` generic over its `Edge`. It turns out that this is tricky. For example, if I edit `Edge` so it has `var reversed: Self {get}`, then in `UnweightedEdge`, I want to do this:

```swift
public var reversed:UnweightedEdge {
    return UnweightedEdge(u: v, v: u, directed: directed)
}
```

But I get an error on the first line:

>Protocol 'Edge' requirement 'reversed' cannot be satisfied by a non-final class ('UnweightedEdge') because it uses 'Self' in a non-parameter, non-result type position

**Comment by davecom** [comment]
Yes, as I'm sure you know Swift generics are still not what they should be which does make it tricky to use protocols as we think we should be able to. I've recently seen a very well known developer say he is just done with protocols for now and going back to class inheritance, because he can't deal with the all of the limitations and intricacies as protocols currently stand. For what it's worth, you can find a version of `Graph` switched over to be a protocol here:
https://github.com/davecom/ClassicComputerScienceProblemsInSwift/blob/master/Classic%20Computer%20Science%20Problems%20in%20Swift.playground/Pages/Chapter%204.xcplaygroundpage/Contents.swift

However, to get that to work in a reasonable way, I had to have `Graph` adopt `class` which is nasty imho.

For now I kind of agree with said well known developer. While doing everything with protocols maybe laudable, it's ultimately not practical given the current state of Swift and the engineering effort required to get it working. So, a compromise where protocols are adopted where it's easy (e.g. `Edge`) is probably as far as it's worth going in Swift 4 land.

**Comment by ZevEisenberg** [comment]
Yep. Worth a revisit for Swift 5!

**Pull request merged**
