### PR TITLE
Some Swift 5 updates

### PR DESCRIPTION
**Pull request by ZevEisenberg**
These are just the easy backwards-compatible changes. I ran into trouble when I tried to convert the project to Swift 5 and then add a compatibility alias for the one function that you use that has changed in Swift 5:

```swift
#if swift(<5)
extension Collection where Element: Equatable {
func firstIndex(of member: Element) -> Index? {
    return index(of: member)
}
#endif
```

When I did this, the compiler was having ambiguity issues with two lines that looked like this:

```swift
let indices = cycle.map({ indexOfVertex($0)! })
```

Wasn't sure how to resolve them. But you should be able to merge the changes in this PR and be a little closer to Swift 5 😄

### CODE REVIEW

**Comment by davecom** [comment]
Thanks, Zev. I'm not sure if we'll ship a release that is both Swift 4 and Swift 5 compatible, or just do a new minor release (2.1?) that is Swift 5 only.

Question—why did you remove a lot of the access modifiers that were public? We want those methods (dfs(), detectCycles, etc.) to be accessible to non-members of the module. My understanding from the Swift book is that " If you define a type’s access level as internal or public (or use the default access level of internal without specifying an access level explicitly), the default access level of the type’s members will be internal." and we don't want them to be internal. Is some kind of warning being raised in Swift 5? I'm probably missing some context here since I haven't installed the Swift 5 betas.

**Comment by ZevEisenberg** [comment]
Yep. Swift 5 marks explicit access modifiers as redundant if they're the same scope as the extension they're in, I think.

Not sure if an update that drops a Swift version would be considered a semver "breaking change" or not, if you care about such things. It should be a relatively minor change to add a compatibility alias, though. We wrote a [blog post](https://www.raizlabs.com/dev/2016/10/swift-2-x-3-0-compatibility/) about this for the Swift 2 → 3 transition, although it mostly still applies.

**Comment by davecom** [comment]
Hmm, I can't find a reference to this change about access modifiers in extensions in the release notes. At least the ones I'm looking at:
https://developer.apple.com/documentation/xcode_release_notes/xcode_10_2_beta_2_release_notes/swift_5_release_notes_for_xcode_10_2_beta_2

And they also haven't updated the book even though the book says it's Swift 5 now. I'm wondering if this was an erroneous warning/error?

And I guess if we want to still support Swift 4.2 from before the change we should leave them in?

I guess I'll need to see the errors that you're seeing for myself in an updated version of Xcode. I may wait until Swift 5 final ships (next month?) to update SwiftGraph. Thanks for the heads up. 

Thanks for the blog post link; I'm going to check it out.

**Comment by ZevEisenberg** [comment]
It could be spurious. But I’d assume that the modifiers were also redundant in Swift 4.x unless a test says otherwise.

From personal experience, I’d recommend giving it a quick run in Xcode 10.2 beta, of for no other reason than to report any bugs when you try to compile.

On that note, SwiftGraph would probably be a good candidate for submission to the Swift source compatibility test suite: https://swift.org/source-compatibility/

**Comment by davecom** [comment]
Thanks for contribution. Merged into a branch for Swift 5/SwiftGraph 2.1.

**Pull request merged**
