### PR TITLE
Directed pseudo forest

### PR DESCRIPTION
**Pull request by ferranpujolcamins**
In this PR I add a subclass of UniqueElementsGraph with the property that vertices have at most one outgoing edge [1].

I also introduce SwiftCheck for property testing.

[1] https://en.wikipedia.org/wiki/Pseudoforest#Directed_pseudoforests

### CODE REVIEW

**Comment by ferranpujolcamins** [comment]
@davecom Now that xcode supports swift packages, do you think we can just get rid of the xcodeproj?

**Comment by davecom** [comment]
Sorry I've been out of touch. I'm going to take a look at this over the weekend. I don't want to get rid of the Xcode project because it has the Mac sample app and it also just makes it easy for people unfamiliar with SPM/Cocoapods to get started.

**Comment by ferranpujolcamins** [comment]
I understand. I'll add the SwiftCheck package on the proj also then.

**Comment by ferranpujolcamins** [comment]
I'm done with the final touches, the PR is ready from my side. Let me know what you think.

**Comment by ferranpujolcamins** [comment]
Found a bug on the graph validation code. I'm writing tests now.

**Comment by davecom** [comment]
Hi @ferranpujolcamins,
Thanks for putting this together. There's good stuff here, but I don't want to add SwiftCheck as a dependency (which in turn has another package as a dependency, which in turn has yet another package as a dependency). We currently have no dependencies that are not shipped with Swift, and I'd like to keep it that way. Especially since SwiftGraph is part of the Swift source compatibility suite, but also because I don't want to start being dependent on other projects as Swift continues to evolve.

Let's put the generators into the main project. Our project is not large enough that we need to start splitting it up into subdivisions.

Can you also add some comments in. I don't know what some of these are supposed to do.

Thanks,
Dave

**Comment by ferranpujolcamins** [comment]
Hi Dave, i understand.

However the Generators also depend ln Swiftcheck.

I will strip the property tests from the PR and leave only
DirectedPseudoForest. Then I will add a bunch of normal tests for it.

I will create a new repo with the property tests and Generators. Then I
will add a reference to the new repo on the readme of SwiftGraph.

I think property tests are important, but I don’t want to create a forkof
SwiftGraph, so I think this is a good compromise.

Would this work for you?

**Comment by ferranpujolcamins** [comment]
@davecom Gentle ping. 

> I will strip the property tests from the PR and leave only
DirectedPseudoForest. Then I will add a bunch of normal tests for it.

Do you think this would fit SwiftGraph?

**Comment by davecom** [comment]
@ferranpujolcamins Sorry for the late reply. I think your plan is good!

**Comment by ferranpujolcamins** [comment]
I'm not finding the time to do this. I'm closing the PR by now. My apologies.

**Pull request closed without merging**
